### ISSUE TITLE
LAMP Server

### ISSUE THREAD

**Issue by Ranthalion** [Ranthalion/rfidLock#17]
Provision LAMP server for web and DB

**Comment by jonathan46000** [comment]
Lamp stack is up on 10.200.200.11.  The servers IP on the private network NIC is 172.12.123.20.  Currently has MariaDB, All PHP5 mods, phpMyAdmin and Apache2 are installed.  SSH is up.  See me for username and password.  If you want anything else installed and set up please let me know.

-Jon L
