### ISSUE TITLE
Automatic Slack invitation

### ISSUE THREAD

**Issue by Ranthalion** [Ranthalion/rfidLock#18]
When a new user is added to the system, they should receive an automated Slack invitation.

**Comment by Matt5sean3** [comment]
I made the self-invite system that's currently hooked up at [hackrva.org](http://hackrva.org/chat-invite/). Reusing the code from that shouldn't be too hard, I'll add in the core part so that it can be called as a function.

**Comment by Ranthalion** [comment]
complete
