### ISSUE TITLE
Public Add Member function

### ISSUE THREAD

**Issue by Ranthalion** [Ranthalion/rfidLock#24]
Create an add member page that does not require authentication and only prompts for email, payment provider, and rfid.  Then check via the payment provider that the new member exists and isn't already in the system.

**Comment by Matt5sean3** [comment]
#9 needs to be done first for this to be possible. Also, are there payment providers other than Paypal that HackRVA uses?

**Comment by Ranthalion** [comment]
Complete with PayPal lookup
